print("Hello World!")
print("Welcome to Personal Intro Program")
name = input("What is your name? ")
age = input("How old are you? ")
city = input("Which city do you live in? ")
hobby = input("What is your favorite hobby? ")

print("\n" + "=" * 40)
print(f"Welcome {name}!")
print(f"You are {age} years old.")
print(f"You live in {city}.")
print(f"Your favorite hobby is {hobby}.")
print("Have a wonderful day!")
print("=" * 40)
